[tool.poetry]
name = "ashfin-loop-cves"
version = "0.1.0"
description = ""
authors = ["Afnan Enayet <afnan@afnan.io>"]
readme = "README.md"
packages = [{include = "ashfin_loop_cves"}]

[tool.poetry.scripts]
loop = "loop:main"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
loguru = "^0.6.0"
rich = "^12.5.1"
click = "^8.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
